#!/bin/bash

# options to be displyed
option0=" Logout"
option1="⏾ Suspend"
option2=" Reboot"
option3=" Shutdown"

# Variable passed to rofi
options="$option0\n$option1\n$option2\n$option3"

selected="$(echo -e "$options" | rofi -theme-str "listview{ lines: 2;}"  -dmenu -p "WARNING: unsaved changes will be lost")"
case $selected in
    $option0)
        systemctl terminate-user $USER;;
    $option1)
        systemctl suspend;;
    $option2)
        systemctl reboot;;
    $option3)
        systemctl poweroff;;
esac
