#!/bin/sh

cd ~/

if [ -f ".config/selexecute.conf" ]; 
then
    printf "~/.config/selexecute detected \n"
else
    printf "WARNING: Config file (~/.config/selexecute.conf) not detected, creating default config file... \n"
    printf 'e="xed" \n f="nemo" \n l="rofi -show drun"  f="strawberry" \n \n s="flameshot gui" \n t="sakura"\n w="vivaldi-stable"\n' > .config/selexecute.conf
fi

source ~/.config/selexecute.conf
help()
{
   printf "selexecute is a program that execute some commands according to you ~/.config/selexecute.conf

Options: 
    editor
    -e  Open text editor

    files
    -f  Open file manager

    launcher
    -l  Open applications launcher

    music
    -m  Open applications menu

    screenshot
    -s  Open screenshooter

    terminal
    -t  Open a terminal emulator

    web
    -w  Open web browser
"
}
editor()
{
$e
}
files()
{
$f
}
launcher()
{ 
$l
}
music()
{ 
$m
}
screenshot()
{ 
$s
}
terminal()
{ 
$t
}
web()
{ 
$w 
}

case "${1}" in
   editor)
      editor;;
   files)
      files;;
   launcher)
      launcher;;
   music)
      music;;
   screenshot)
      screenshot;;
   terminal)
      terminal;;
   web)
      web;;
   help)
      help;;
esac

while getopts ":eflmstwh" option; do
   case $option in
      e) 
         editor
         exit;;
      f) 
         files
         exit;;
      l)
         launcher
         exit;;
      m)
         music
         exit;;
      s)
         screenshot
         exit;;
      t)
         terminal
         exit;;
      w)
         web
         exit;;
      h)
         help
         exit;;
esac done
