#!/bin/sh
cd ~/
xrdb ~/.Xresources &
#xsetbg ~/.local/share/slnxwm/extra/wallpaper.png &
hsetroot -solid '#2a2a2a' &
#picom --legacy-backend
pipewire &
sleep 1 &&
wireplumber &
sleep 1 &&
pipewire-pulse &
#xrandr --output HDMI-1 --mode 1440x900 --rate 75


################## Statusbar
while true; do
   xsetroot -name "󰕾 : $(pamixer --get-volume-human)   󱑍 : $( date +"%I:%M %p" ) "

#Bar with Nerd Information

#xsetroot -name "| 󰝚 :  $(pacmd list-sink-inputs | grep -oP '(?<=media.artist = ).*') - $(pacmd list-sink-inputs | grep -oP '(?<=media.title = ).*') | 󰕾 : $(pamixer --get-volume-human) | 󰍛 : $(free -h --kilo | awk '/^Mem:/ {print $3 "/" $2}') | 󱑍 : $( date +"%I:%M %p" ) "

# "| 󰝚 :  $(pacmd list-sink-inputs | grep -oP '(?<=media.artist = ).*') - $(pacmd list-sink-inputs | grep -oP '(?<=media.title = ).*') | 󰕾 : $(pamixer --get-volume-human) | 󰍛 : $(free -h --kilo | awk '/^Mem:/ {print $3 "/" $2}') |󰏈 : $(sensors|grep 'Core 0'|awk '{print $3}' ) | 󱑍 : $( date +"%I:%M %p" ) "

   sleep 2    # Update every second
done &

################################3
# run dwm ( do not remove this )
dwm
