#!/bin/sh
cd ~/
 /lib/mate-polkit/polkit-mate-authentication-agent-1 &
picom & 
devmon &
xrdb merge ~/.Xresources &
feh --bg-fill ~/.local/share/slnxwm/extra/wallpaper.png &

################## Statusbar
while true; do
  # xsetroot -name "墳: $(pamixer --get-volume-human)   : $( date +"%I:%M %p" ) "

#Bar with Nerd Information  

xsetroot -name "| :  $(pacmd list-sink-inputs | grep -oP '(?<=media.artist = ).*') - $(pacmd list-sink-inputs | grep -oP '(?<=media.title = ).*') | 墳: $(pamixer --get-volume-human) | : $(free -h --kilo | awk '/^Mem:/ {print $3 "/" $2}') | : $( date +"%I:%M %p" ) "

# "| :  $(pacmd list-sink-inputs | grep -oP '(?<=media.artist = ).*') - $(pacmd list-sink-inputs | grep -oP '(?<=media.title = ).*') | 墳: $(pamixer --get-volume-human) | : $(free -h --kilo | awk '/^Mem:/ {print $3 "/" $2}') |: $(sensors|grep 'Core 0'|awk '{print $3}' ) | : $( date +"%I:%M %p" ) "

   sleep 2    # Update every second
done &

################################3
# run dwm ( do not remove this )
dwm
